config/routes.rb
BizExplainer::Application.routes.draw do

  resources :messages

  resources :users
  resources :sessions
  resources :projects

  # You can have the root of your site routed with "root"
  root 'projects#index'

    get 'admin' => 'projects#admin', as: 'admin'
    get 'signup' => 'users#new', as: 'sign_up'
    get 'login' => 'sessions#new', as: 'log_in'
    get 'logout', to: 'sessions#destroy', as: 'logout'




  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end
  
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/asset.rb
class Asset < ActiveRecord::Base
  belongs_to :project

  has_attached_file :document, url: "/documents/:filename", path: ":rails_root/public/documents/:filename"

end

app/models/deliverable.rb
class Deliverable < ActiveRecord::Base
  belongs_to :project

  has_attached_file :document, url: "/final_documents/:filename", path: ":rails_root/public/final_documents/:filename"
end

app/models/message.rb
class Message < ActiveRecord::Base

  belongs_to :project
  belongs_to :user


end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :messages, dependent: :destroy
  has_many :assets, dependent: :destroy
  has_many :deliverables, dependent: :destroy

  accepts_nested_attributes_for :assets
  accepts_nested_attributes_for :deliverables


  def self.get_all_projects(order = :desc)
      Project.all.order(created_at: order)
  end

end

app/models/user.rb
require 'digest/md5'

class User < ActiveRecord::Base
  has_secure_password

  has_many :projects
  has_many :messages

  before_validation :prep_email
  before_save :create_avatar_url

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true

  def pending_projects
    self.projects.where(project_status: 'Pending')
  end

  def processing_projects
    self.projects.where(project_status: 'Processing')
  end

  def completed_projects
    self.projects.where(project_status: 'Complete')
  end



  private

  def prep_email
    self.email = self.email.strip.downcase if self.email
  end

  def create_avatar_url
    self.avatar_url = "http://www.gravata.com/avatar/#{Digest::MD5.hexdigest(self.email)}?s=50"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :project_link

  private

  def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def project_link
    if current_user.user_type == 'user'
      projects_path
    else
      admin_path
    end
  end

  def admin?
    if current_user.user_type == 'admin'
      true
    else
      false
    end

  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index

  end

  def new
    @message = Message.new
    @user = current_user
  end


  def create
    message = Message.new(message_params)
    message.user_id = current_user.id
    message.read = false
    #project.document_file_name = "User_#{current_user.id.to_s}"+project.document_file_name

    if message.save
      redirect_to :controller => 'projects', :action => 'show', :id => message.project_id.to_s, :redirect => 'yes'
    else
      render 'new'
    end
  end

  def message_params
    params.require(:message).permit(:content,:project_id)
  end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :require_login


  def index
    if admin?
      @projects = Project.get_all_projects
      render :admin
    else
      @projects = current_user.projects
      project_pending = current_user.pending_projects
      @project_pending = project_pending.count

      project_processing = current_user.processing_projects
      @project_processing = project_processing.count

      project_completed = current_user.completed_projects
      @project_completed = project_completed.count

    end

  end

  def admin
    if admin?
      @projects = Project.get_all_projects
    else
      @projects = current_user.projects
      render :index
    end
  end

  def new
    @project = Project.new
    @user = current_user
    4.times { @project.assets.build }
  end

  def create
    project = Project.new(project_params)
    project.user_id = current_user.id
    project.project_status = 'Pending'
    project.payment_status = 'Pending'
    #project.document_file_name = "User_#{current_user.id.to_s}"+project.document_file_name.to_s

    if project.save
      redirect_to root_path, :notice => 'Project Created Successfully!'
    else
      render 'new'
    end

  end

  def destroy
    project = Project.find(params[:id])
    project.destroy
    redirect_to admin_path
  end

  def update
    project = Project.find(params[:id])

    message_params = Hash.new
    message_params[:content] = 'Project Completed'
    message_params[:project_id] = params[:id]
    message_params[:user_id] = current_user.id

    message = Message.new message_params
    message.save

    project.update_attributes update_params
    redirect_to project_path
  end

  def show
    Time.zone = cookies[:bz_time_zone]
    @message = Message.new
    @project_id = params[:id]

    @project = Project.find(@project_id)
    @requirements = @project.requirements
    @project_status = @project.project_status
    @assets = @project.assets
    @deliverables = @project.deliverables

    @messages = Message.where(project_id: @project_id).order('created_at ASC')

    @messages.each do |message|
      message.read = true if params[:redirect] != 'yes' && message.user.id != current_user.id    #mark as read if the user has already read the message
      message.save
    end

    1.times { @deliverables.build unless @deliverables.present? }

  end

  private

  def project_params
    params.require(:project).permit(:title, :video_duration, :voice_over, :requirements, assets_attributes: [:document])
  end

  def update_params
    params.require(:project).permit(:project_status, deliverables_attributes: [:document])
  end

  def require_login
    redirect_to sign_up_path unless session[:user_id]
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_email params[:email]

    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url if user.user_type == 'user'
      redirect_to admin_url if user.user_type == 'admin'
    else
      flash[:error] = "Invalid Email and Password."
      redirect_to root_url
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged Out."
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  layout "registration"

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
    @user.user_type = "user"

  	   if @user.save
         session[:user_id] = @user.id
  		    redirect_to root_path, :notice => "Signed Up!"
          UserMailer.registration_confirmation(@user).deliver
  	   else
		      render 'new'
	     end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
  <div id="footer">
    <div class="row">

    </div>

  </div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="<%= project_link %>"><img src="/assets/img/logo.png" alt=""/></a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li><a href="<%= project_link %>"><span class="glyphicon glyphicon-list-alt"></span><strong>Projects</strong></a></li>
      <li><a href="<%= new_project_path %>"><span class="glyphicon glyphicon-plus"></span><strong>Create a New Project</strong></a></li>

    </ul>

    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">

        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span><%= current_user.name %><b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#"><span class="glyphicon glyphicon-cog"></span>Profile Settings</a></li>
          <li class="divider"></li>
          <li><a href="<%= logout_path %>"><span class="glyphicon glyphicon-log-out"></span>Logout</a></li>
        </ul>
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BizExplainer</title>
  <link rel="stylesheet" href="/assets/css/bootstrap.css"/>
  <link rel="stylesheet" href="/assets/css/style.css"/>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <%= javascript_include_tag "application" %>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <script src="/assets/js/bootstrap.js"></script>
  <script src="/assets/js/time_zone.js"></script>
  <script src="/assets/js/script.js"></script>
  <!-- [if lt IE 9] -->

</head>
<body>
   <!-- <%= debug(params) %> -->
    <div id="wrap">
      <%= render 'layouts/header' %>
      <div class="container" id="main">

        <%= yield %>
        <div id="push"></div>
      </div>

    </div>

    <%= render 'layouts/footer' %>

</body>
</html>

app/views/layouts/registration.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BizExplainer</title>
  <link rel="stylesheet" href="/assets/css/bootstrap.css"/>
  <link rel="stylesheet" href="/assets/css/style.css"/>

  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <script src="/assets/js/bootstrap.js"></script>
  <!-- [if lt IE 9] -->

</head>
<body>

        <div id="wrap">
          <div class="container" id="main">
            <img src="/assets/img/bizexplainer.png" alt=""/>
            <%= yield %>

            <div id="push"></div>
          </div>
        </div>

        <script src="/assets/js/script.js"></script>

        <%= render 'layouts/footer' %>
</body>
</html>

app/views/messages/new.html.erb
<div id="message_content" >

  <div class="panel panel-primary">

    <div class="panel-heading">Discuss Your Project</div>
    <div class="panel-body project-panel">
      <%= form_for @message, html: {role: "form", multipart: true} do |f| %>

          <div class="form-group">
            <%= f.text_area :content, rows: "8", class: "form-control",  placeholder: "Type your message here..." %>

          </div>

          <div class="form-group">

            <%= f.submit "Submit", class: "btn btn-primary" %>

          </div>


      <% end %>
    </div>
    <div class="panel-footer"></div>
  </div>

</div>

app/views/projects/admin.html.erb
<div id="project_content">

  <div class="container">
    <% flash.each do |name, msg| %>
        <div class="alert alert-success row"> <strong><%= msg %></strong>
          <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a></div>
    <% end %>


    <div class="jumbotron row">

      <div class="col-md-6">
        <h2>Welcome!</h2>

        <p>Thanks for Signing Up.Please watch the short video to get started.</p>

        <p><a class="btn btn-success btn-lg" role="button" href="<%= new_project_path %>">Get Started</a></p>
      </div>
      <div id="mainVideo">
        <iframe src="http://player.vimeo.com/video/23237102?title=0&amp;byline=0&amp;portrait=0&amp;color=ffffff" width="500" height="281" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
      </div>
    </div>


  </div>

  <% if @projects.count > 0 %>
      <table class="table table-striped table-bordered table-responsive">
        <tr>
          <th class="text-muted">User</th>
          <th class="text-muted">Project Title</th>
          <th class="text-muted">Project Status</th>
          <th class="text-muted">Payment Status</th>
          <th class="text-muted">Delete</th>
        </tr>
        <% @projects.each do |project| %>
            <% total_messages = project.messages.where(read: false).where.not(user_id: current_user.id).count %>
            <% has_read = total_messages > 0 ? "badge not-read pull-right":"badge pull-right"  %>
            <tr>
              <td><strong><%= project.user.name %></strong></td>
              <td data-width="200"><%= link_to project.title, project_path(project) %> <span class="<%= has_read %>"><%= total_messages %></span></td>
              <% if project.project_status == 'Pending' %>
                <td><span class="label label-danger"><%= project.project_status %></span></td>
              <% elsif project.project_status == 'Processing' %>
                  <td><span class="label label-warning"><%= project.project_status %></span></td>
              <% else %>
                  <td><span class="label label-success"><%= project.project_status %></span></td>
              <% end %>

              <td>
                <span class="label label-danger"><%= project.payment_status %></span><a href="#" class="btn btn-success btn-small pay-button" role="button"><span class="glyphicon glyphicon-usd"></span><strong>Pay
                Now</strong></a></td>
              <td><%= button_to "Delete", project, confirm: "Are you sure you want to delete?", method: :delete, class: 'btn btn-danger btn-small' %></td>
            </tr>
        <% end %>
      </table>

  <% end %>


</div>

app/views/projects/create.html.erb
<div id="project_content" class="centered content">

<%= @project_title %>
Hello there


</div>

app/views/projects/index.html.erb
<div id="project_content">

  <div class="container">
    <% flash.each do |name, msg| %>
        <div class="alert alert-success row"> <strong><%= msg %></strong>
          <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a></div>
    <% end %>

    <% if @projects.count == 0 %>

    <div class="jumbotron row">

      <div class="col-md-6">
        <h2>Welcome!</h2>

        <p>Thanks for Signing Up.Please watch the short video to get started.</p>

        <p><a class="btn btn-success btn-lg" role="button" href="<%= new_project_path %>">Get Started</a></p>
      </div>
      <div id="mainVideo">
        <iframe src="http://player.vimeo.com/video/23237102?title=0&amp;byline=0&amp;portrait=0&amp;color=ffffff" width="500" height="281" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
      </div>
    </div>

   <% end %>

    <% if @projects.count != 0 %>

        <div class="row jumbotron project-status">

          <div class="col-xs-3 col-md-3 project-stat">
               <h1 class="title-pending">
                 Projects Pending
               </h1>
               <div class="number-stat-pending number-stat">
                 <%= @project_pending %>
               </div>
         </div>

          <div class="col-xs-3 col-md-3 col-md-offset-1 col-xs-offset-1 project-stat">
                <h1 class="title-processing">
                  Projects Processing
                </h1>
            <div class="number-stat-processing number-stat">
              <%= @project_processing %>
            </div>

          </div>

          <div class="col-xs-3 col-md-3 col-md-offset-1 col-xs-offset-1 project-stat">
               <h1 class="title-completed">
                Projects Completed
               </h1>
            <div class="number-stat-completed number-stat">
              <%= @project_completed %>
            </div>

          </div>


        </div>

    <% end %>

  </div>

  <% if @projects.count > 0 %>
      <table class="table table-striped table-bordered table-responsive">
        <tr>
          <th class="text-muted">Project Title</th>
          <th class="text-muted">Project Status</th>
          <th class="text-muted">Payment Status</th>
        </tr>
        <% @projects.each do |project| %>
            <% total_messages = project.messages.where(read: false).where.not(user_id: current_user.id).count %>
            <% has_read = total_messages > 0 ? "badge not-read pull-right":"badge pull-right"  %>

            <tr>
              <td><strong><span class="project-title"><%= link_to project.title, project_path(project) %></span></strong><span class="<%= has_read %>"><%= total_messages %></span></td>
              <% if project.project_status == 'Pending' %>
                  <td><span class="label label-danger"><%= project.project_status %></span></td>
              <% elsif project.project_status == 'Processing' %>
                  <td><span class="label label-warning"><%= project.project_status %></span></td>
              <% else %>
                  <td><span class="label label-success"><%= project.project_status %></span></td>
              <% end %>
              <td>
                <span class="label label-danger"><%= project.payment_status %></span><a href="#" class="btn btn-success btn-small pay-button" role="button"><span class="glyphicon glyphicon-usd"></span>Pay
                Now</a></td>
            </tr>
        <% end %>
      </table>

  <% end %>


</div>

app/views/projects/new.html.erb
	<div id="project_content" >

      <div class="panel panel-primary create-project">

        <div class="panel-heading"><h3 class="panel-title">Create A Project</h3></div>
        <div class="panel-body project-panel">
          <%= form_for @project, html: {role: "form", multipart: true} do |f| %>

              <div class="form-group">
                <label for="title">Project Title</label>
                <%= f.text_field :title, placeholder: 'Your Project Title', class: "form-control" %>
              </div>

              <div class="form-group">
                <label for="video_duration">How, long do you want your video to be?</label>
                <div class="radio">


                  <%= f.radio_button :video_duration, '1.0', :checked => true, class: 'inline' %>
                  <%= label :video_duration, 'One Minute', class: 'inline' %>
                </div>
                <div class="radio">
                  <%= f.radio_button :video_duration, '2.0' %>
                  <%= label :video_duration, 'Two Minute' %>
                </div>

              </div>


              <div class="form-group">
                <label for="video_duration">Choose a gender for your voiceover</label>
                <div class="radio">


                  <%= f.radio_button :voice_over, 'male', :checked => true %>
                  <%= label :voice_over, 'Male' %>
                </div>
                <div class="radio">
                  <%= f.radio_button :voice_over, 'female' %>
                  <%= label :voice_over, 'Female' %>
                </div>

              </div>

              <div class="form-group">
                <label for="requirements">Explain your requirements</label>
                <%= f.text_area :requirements, rows: "8", class: "form-control",  placeholder: "Type your message here..." %>

              </div>

              <div class="form-group">
                <label for="document">Attachments</label>

                <div class="container attachments">
                  <%= f.fields_for :assets do |asset| %>

                      <div class="row file-row">
                       <div class="col-sm-4"><%= asset.file_field :document, class: "form-control" %></div> <div class="col-sm-6 img remove attach">
                        <a href="#"></a><i class="fa fa-minus-square fa-2x"></i></div>

                        </div>

                  <% end %>
                  <div class="attach col-sm-2"><i class="fa fa-plus-square fa-2x"></i><span></span><span class="attach-text"><strong>Attach More...</strong></span></div>

                </div>

              </div>

              <div class="form-group">

                <%= f.submit "Create", class: "btn btn-success" %>

              </div>


          <% end %>
        </div>
      </div>

	</div>
    <script src="/assets/js/script.js"></script>

app/views/projects/show.html.erb
<div id="message_content">

  <div class="panel panel-default">
    <div class="panel-heading">
      <div><span class="panel-title text-muted"><strong>Your Requirements</strong></span>


        <span class="attachment"><% if @deliverables.count > 0 %>

            <div class="btn-group">

              <button class="btn btn-default btn-sm dropdown-toggle" type="button" data-toggle="dropdown">
                <span class="glyphicon glyphicon-cloud-download"></span>
                <strong>Downloads<span class="caret"></span></strong>
              </button>

              <ul class="dropdown-menu">
                <% @deliverables.each do |deliverable| %>

                    <li> <%= link_to deliverable.document_file_name, deliverable.document.url %> </li>

                <% end %>
              </ul>
            </div>


              </span><% end %>

          <span class="attachment"><% if @assets.count > 0 %>


            <div class="btn-group">

              <button class="btn btn-default btn-sm dropdown-toggle" type="button" data-toggle="dropdown">
                <span class="glyphicon glyphicon-paperclip"></span>
                <strong>Attachments <span class="caret"></span></strong>
              </button>

              <ul class="dropdown-menu">
                <% @assets.each do |asset| %>

                    <li> <%= link_to asset.document_file_name, asset.document.url %> </li>

                <% end %>
              </ul>
            </div>


                </span><% end %>
            </div>
    </div>

    <div class="panel-body">
      <%= @requirements if @requirements %>
    </div>
  </div>


  <% if current_user.user_type == 'admin' %>

      <% if @project_status == 'Pending' %>

          <div class="panel panel-danger admin-panel">

      <% elsif @project_status== 'Processing' %>
          <div class="panel panel-warning admin-panel">
      <% else %>
          <div class="panel panel-success admin-panel">
      <% end %>

      <div class="panel-heading">
        <div><span class="panel-title text-muted">Project Status: <%= @project_status %></span><span class="attachment"><% if @deliverables.count > 0 %>

            <span class="glyphicon glyphicon-paperclip"></span>
            <div class="btn-group">

              <button class="btn btn-default btn-sm dropdown-toggle" type="button" data-toggle="dropdown">
                Deliverables <span class="caret"></span>
              </button>

              <ul class="dropdown-menu">
                <% @deliverables.each do |deliverable| %>

                    <li> <%= link_to deliverable.document_file_name, deliverable.document.url %> </li>

                <% end %>
              </ul>
            </div>


              </span><% end %></div>
      </div>

      <div class="panel-body">
        <%= form_for(@project) do |f| %>
            <div class="form-group">
              <label for="project_status" class="control-label">Project Status</label>

              <div>
                <%= f.select :project_status, ['Pending', 'Processing', 'Complete'], class: "form-control" %>
              </div>


            </div>

            <div class="form-group">

              <label for="project_status" class="control-label">Deliver Completed Video</label>

              <div>
                <%= f.fields_for :deliverables do |d| %>

                    <div class="row file-row">
                      <div class="col-sm-4"><%= d.file_field :document, class: "form-control" %></div>

                    </div>
                <% end %>

              </div>


            </div>

            <div class="form-group">

              <% if @project_status == 'Pending' %>

                  <%= f.submit "Submit", class: "btn btn-danger" %>

              <% elsif @project_status== 'Processing' %>
                  <%= f.submit "Submit", class: "btn btn-warning" %>
              <% else %>
                  <%= f.submit "Submit", class: "btn btn-success" %>
              <% end %>


            </div>

        <% end %>

      </div>
      </div>

  <% end %>



  <% if @messages %>
      <% @messages.each do |message| %>

          <% if message.user.user_type == "admin" %>
              <div class="panel panel-warning">
          <% else %>
              <div class="panel panel-success">
          <% end %>

          <div class="panel-heading">
            <h3 class="panel-title"><%= message.user.name %><span class="message-date"><%= message.created_at.strftime("%B %d at %I:%M %p") %></span>
            </h3>
          </div>

          <div class="panel-body">
            <%= simple_format(message.content) %>
          </div>

          </div>
      <% end %>
  <% end %>


  <div class="well">

    <div class="panel-heading"><h3 class="panel-title">Discuss Your Project</h3></div>
    <div class="panel-body project-panel">
      <%= form_for @message, html: {role: "form", multipart: true} do |f| %>

          <div class="form-group">
            <%= f.text_area :content, rows: "8", class: "form-control", placeholder: "Type your message here..." %>

          </div>

          <div class="form-group">
            <%= f.submit "Submit", class: "btn btn-success" %>

          </div>

          <%= f.hidden_field :project_id, value: @project_id %>

      <% end %>
    </div>
  </div>
  </div>
  </div>
  </div>
</div>

app/views/users/new.html.erb
<div id="register_content">

<div class="row register">

  <div class="col-md-6">

    <div class="panel panel-success login-panel">
      <div class="panel-heading login-heading"><strong>Log In</strong></div>

      <div class="panel-body">
          <%= form_tag sessions_path, role: "form", class: "form-horizontal"   do  %>
            <ul>
            <% flash.each do |name, msg| %>
                  <li class="alert alert-danger"> <%= msg %> <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a></li>
            <% end %>
           </ul>
          <div class="form-group">

            <label for="email" class="col-sm-2 control-label">Email</label>

            <div class="col-sm-10">
              <%= text_field_tag :email, params[:email], class: "form-control", id: "email", placeholder: "Email" %>
            </div>
          </div>
          <div class="form-group">
            <label for="password" class="col-sm-2 control-label">Password</label>

            <div class="col-sm-10">
              <%= password_field_tag :password, params[:password], class: "form-control", id: "password", placeholder: "Password" %>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <div class="checkbox">
                <label>
                  <input type="checkbox"> Remember me
                </label>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <%= submit_tag 'Sign In', class: "btn btn-success" %>
            </div>
          </div>
        <% end %>
      </div>

    </div>

  </div>

  <div class="col-md-6">

    <div class="panel panel-warning register-panel">
      <div class="panel-heading register-heading"><strong>Register</strong></div>

      <div id="signup">
        <%= form_for @user, html: {role: "form"} do |f| %>
            <% if @user.errors.any? %>
                <ul>
                  <% @user.errors.full_messages.each do |e| %>

                      <li class="alert alert-danger"> <%= e %> <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a></li>
                  <% end %>

                </ul>
            <% end %>
            <div class="form-group">
              <label for="email">Email Address</label>
              <%= f.text_field :email, placeholder: "Email", type: "email", class: "form-control", id: "email" %>
            </div>
            <div class="form-group">
              <label for="email">Name</label>
              <%= f.text_field :name, placeholder: "Name", type: "name", class: "form-control", id: "name" %>
            </div>
            <div class="form-group">
              <label for="password">Password</label>
              <%= f.password_field :password, placeholder: "Password", type: "password", class: "form-control", id: "password" %>
            </div>
            <div class="form-group">
              <label for="password_confirmation">Confirm Password</label>
              <%= f.password_field :password_confirmation, placeholder: "Confirm Password", type: "password", class: "form-control", id: "password_confirmation" %>
            </div>

            <%= f.submit "Create an Account", class: "btn btn-warning" %>
        <% end %>

      </div>

    </div>

  </div>


</div>

</div>